---
title: "Religion Data Preprocessing"
format:
    html:
        embed-resources: true
---

## Preprocessing the Religious Survey Data
```{python}
import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt
```

#### Reading in the File
```{python}
# reading in the file
religion = pd.read_csv("../data/2023-24-Religious-Landscape-Study-Dataset-Public-Use-File/2023-24 RLS Public Use File Feb 19.csv")
```

#### Understanding the Data
```{python}
# number of observations
print("-----------------")
print("DATA SHAPE:")
print(religion.shape)
```

#### Dropping Variables
```{python}
# remove the restricted value
religion = religion.loc[:, religion.isnull().sum() != 36908]

# droppping the weight variables and year
religion = religion.loc[:, ~religion.columns.str.startswith('REPWT_')]
religion = religion.drop(columns=['WEIGHT', 'YEAR_FROM_CODATE'])
```

#### Dealing with Missing Values
```{python}
# understanding missing values
print("-----------------")
print("MISSING VALUES:")
missing_values = religion.isnull().sum()
print(missing_values[missing_values > 0])

# deleting all variables with missing values
religion_nona = religion.dropna(axis=1)
missing_values = religion_nona.isnull().sum()
print(missing_values[missing_values > 0])

#removing the RELCON variables (most responses are not sure/refuse)
religion_nona = religion_nona.drop(columns=['RELCON_A', 'RELCON_B', 'RELCON_C', 'RELCON_D', 'RELCON_E'])

# seeing how many other observations:
print("-----------------")
print("VARIABLES WITH 99 RESPONSES:")
for column in religion_nona.columns:
  count_greater_15 = (religion_nona[column] == 99).sum()
  if count_greater_15 > 0:
    print(f"{column}: {count_greater_15}")
```

#### Dealing with Refused Responses
```{python}
# seeing how many 77
print("-----------------")
print("VARIABLES WITH 77 RESPONSES:")
for column in religion_nona.columns:
  count_greater_15 = (religion_nona[column] == 77).sum()
  if count_greater_15 > 0:
    print(f"{column}: {count_greater_15}")

# seeing how many 98
print("-----------------")
print("VARIABLES WITH 98 RESPONSES:")
for column in religion_nona.columns:
  count_greater_15 = (religion_nona[column] == 98).sum()
  if count_greater_15 > 0:
    print(f"{column}: {count_greater_15}")

# 1) DELETE ANY ROW WITH 99 AS A RESPONSE
# delete any row with 99
religion_nona99 = religion_nona[(religion_nona != 99).all(axis=1)]

# final check for missing/anamolies
print("-----------------")
print("CHECK FOR ISSUES:")
for column in religion_nona99.columns:
  count_greater_15 = (religion_nona99[column] > 15).sum()
  if count_greater_15 > 0:
    print(f"{column}: {count_greater_15}")
```


#### Final Check of Dataset
```{python}
# dropping climate question and religion raised in:
# dropping ID number
religion_nona99 = religion_nona99.drop(columns=['CLIM1A', 'FRMREL', 'P_SUID'])

# tabling the outcomes
print("-----------------")
print("CATEGORICAL COUNTS FOR OUTCOME VARIABLES:")
print("CURREL:")
print(religion_nona99['CURREL'].value_counts())
print("\nRELTRAD:")
print(religion_nona99['RELTRAD'].value_counts())

# dropping the others and refusals from RELTRAD and CURREL
religion_nona99 = religion_nona99[
  ~religion_nona99['CURREL'].isin([40002, 90001, 90002, 900000])
]
religion_nona99 = religion_nona99[
  ~religion_nona99['RELTRAD'].isin([40002, 90001, 90002, 900000])
]

# dropping the unaffliated variable
religion_nona99 = religion_nona99.drop(columns=['UNAFFILDETAIL'])

# final observations and variables
print("-----------------")
print("FINAL NUMBER OF OBSERVATIONS:", religion_nona99.shape[0])
print("FINAL NUMBER OF VARIABLES:", religion_nona99.shape[1])
print("-----------------")

# saving the dataset
religion_nona99.to_csv("../data/religion_data_no99.csv", index=False)
```

**Outcome Variables**: currel/reltrad (current religion or religious tradition) 
    already broken into categories

**Type**: Multi-Class Classification 

**Main Predictor Variables**:
- health/happiness/family life
- views on political/societal topics
- views on evolution/science/climate change
- relgious/spiritual level
- religious involvement/attendance
- religious beliefs (heaven/hell/god)
- how involved spiritually
- marital/children status
- views on churches in society/church and state
- education/work
- race
- political affliation
- gender
- family income